grid:
  cols_per_row: [17, 17, 17]
  anchor_left:
  - { x: 154, y: 66 }
  - { x: 123, y: 733 }
  - { x: 104, y: 1419 }
  anchor_right:
  - { x: 2740, y: 66 }
  - { x: 2766, y: 733 }
  - { x: 2791, y: 1419 }
  roi: { width: 150, height: 200 }
yellow_hsv:
  lower: [10, 140, 30]
  upper: [50, 255, 255]
rod: { min_mask_area: 50 }
junction:
  bottom_anchor_percentile: 99
  search_region:
    y_window: { up_px: 60, down_px: 40 }
    strips: { center_offset_x_px: 20, width_px: 28 }
  white:
    - { S_max: 30, V_min: 110 }
    - { S_max: 30, V_min: 100 }
    - { S_max: 30, V_min: 90 }
  split:
    smooth_half_window_rows: 3
    min_rows: { above: 3, below: 3 }
  height: { max_upward_deviation_px: 20 }
band:
  y0: 3
  y1: 30
  half_width: 30
  H_low: 0
  H_high: 179
  smooth_half_win: 2
  S_thr: 30
  min_width: 10
  max_width: 0
  use_median: false
offset: { offset_base: 4, offset_tol: 12 }
overlay:
  # Colors are BGR integers (OpenCV).
  ok_bgr: [0, 200, 0]
  ng_bgr: [0, 0, 220]
  line_width: 3
dbg: { show_roi: false, show_mask: false, show_strips: false, show_band: false }
